events {
    worker_connections 1024;
}

http {
    server {
        # Pre-configured to unprivileged port 8080 (Vanilla no-error)
        listen 8080;
        server_name localhost;

        location / {
            root html;
            index index.html;
        }
    }
}
